#! /bin/sh

HERE=$(cd "$(dirname "$0")" && pwd)

if [ $# -ne 1 ]; then
    echo "usage: $(basename "$0") file.s"
    exit 1
fi

asm=$1

rm -f "${asm%.s}.obj" &&
    python3 "$HERE"/assembleur/asm.py "$asm" &&
    test -f "${asm%.s}.obj" &&
    "$HERE"/simulateur/LEIA -q "${asm%.s}.obj"
